// NumberInput.spec.ts — Component specification
// specHash: PLACEHOLDER

import type { ComponentSpec } from '../../../spec-type';

export const spec = {
  schemaVersion: 7 as const,
  name: 'NumberInput',
  componentClass: 'input_plain' as const,
  category: 'forms',
  description: 'Numeric input with increment/decrement stepper buttons, controlled/uncontrolled value, format/parse support, and hold-to-repeat',

  synonyms: ['number field', 'numeric', 'spinner input', 'stepper input', 'quantity', 'spinbutton'],
  families: {
    behavior:  ["form-input"],
    state:     ["controlled-value"],
    a11y:      ["none"],
  },

  compound: false,
  rootElement: 'div',
  slots: [
    { name: 'root', element: 'div', description: 'Wrapper div containing input, icon, and controls' },
    { name: 'input', element: 'input', description: 'Native text input with numeric role and inputMode=decimal' },
    { name: 'iconLeft', element: 'span', description: 'Optional left icon slot' },
    { name: 'controls', element: 'div', description: 'Container for increment/decrement stepper buttons' },
    { name: 'increment', element: 'button', description: 'Increment button with chevron-up icon' },
    { name: 'decrement', element: 'button', description: 'Decrement button with chevron-down icon' },
  ],

  subComponents: [],

  props: [
    { name: 'variant', type: "'outlined' | 'filled'", default: "'outlined'", moveSpecific: true, description: 'Visual variant' },
    { name: 'size', typeRef: 'Size', default: "'md'", moveSpecific: true, description: 'Input size' },
    { name: 'value', type: 'number | string', moveSpecific: true, description: 'Controlled numeric value' },
    { name: 'defaultValue', type: 'number | string', moveSpecific: true, description: 'Default value (uncontrolled)' },
    { name: 'onValueChange', type: '(value: number | undefined, displayValue: string) => void', moveSpecific: true, description: 'Called when value changes with both numeric and display string' },
    { name: 'min', type: 'number', moveSpecific: true, description: 'Minimum allowed value' },
    { name: 'max', type: 'number', moveSpecific: true, description: 'Maximum allowed value' },
    { name: 'step', type: 'number', default: '1', moveSpecific: true, description: 'Increment/decrement step amount' },
    { name: 'shiftStep', type: 'number', moveSpecific: true, description: 'Step amount when Shift key held (defaults to step * 10)' },
    { name: 'clampBehavior', type: "'blur' | 'strict' | 'none'", default: "'blur'", moveSpecific: true, description: 'When to clamp value to min/max range' },
    { name: 'allowDecimal', type: 'boolean', default: 'true', moveSpecific: true, description: 'Allow decimal point in input' },
    { name: 'decimalScale', type: 'number', moveSpecific: true, description: 'Number of decimal places to display' },
    { name: 'allowNegative', type: 'boolean', default: 'true', moveSpecific: true, description: 'Allow negative numbers' },
    { name: 'hideControls', type: 'boolean', default: 'false', moveSpecific: true, description: 'Hide increment/decrement buttons' },
    { name: 'invalid', type: 'boolean', moveSpecific: true, description: 'Invalid state with error border styling' },
    { name: 'width', type: "React.CSSProperties['width']", moveSpecific: true, description: 'Custom width override' },
    { name: 'iconLeft', type: 'React.ReactNode', moveSpecific: true, description: 'Optional icon rendered before input' },
    { name: 'prefix', type: 'string', moveSpecific: true, description: 'Prefix text prepended to display value (e.g. "$")' },
    { name: 'suffix', type: 'string', moveSpecific: true, description: 'Suffix text appended to display value (e.g. "%")' },
    { name: 'labels', type: 'Partial<NumberInputLabels>', moveSpecific: true, description: 'Override aria labels for stepper buttons' },
    { name: 'formatValue', type: '(v: number) => string', moveSpecific: true, description: 'Custom value formatter for display' },
    { name: 'parseValue', type: '(s: string) => number | undefined', moveSpecific: true, description: 'Custom value parser from display string' },
    { name: 'disabled', type: 'boolean', moveSpecific: false, description: 'Disabled state' },
    { name: 'readOnly', type: 'boolean', moveSpecific: false, description: 'Read-only state (hides controls)' },
    { name: 'placeholder', type: 'string', moveSpecific: false, description: 'Input placeholder text' },
    { name: 'name', type: 'string', moveSpecific: false, description: 'Form input name' },
    { name: 'id', type: 'string', moveSpecific: false, description: 'Input element id' },
    { name: 'required', type: 'boolean', moveSpecific: false, description: 'Required state' },
    { name: 'autoFocus', type: 'boolean', moveSpecific: false, description: 'Auto-focus on mount' },
    { name: 'onChange', type: 'React.ChangeEventHandler<HTMLInputElement>', moveSpecific: false, description: 'Input change handler' },
    { name: 'onFocus', type: 'React.FocusEventHandler<HTMLInputElement>', moveSpecific: false, description: 'Input focus handler' },
    { name: 'onBlur', type: 'React.FocusEventHandler<HTMLInputElement>', moveSpecific: false, description: 'Input blur handler' },
    { name: 'onKeyDown', type: 'React.KeyboardEventHandler<HTMLInputElement>', moveSpecific: false, description: 'Input keydown handler' },
    { name: 'className', type: 'string', moveSpecific: false, description: 'CSS class name' },
    { name: 'style', type: 'React.CSSProperties', moveSpecific: false, description: 'Inline styles' },
  ],

  anatomy: {
    slot: 'root',
    dataAttributes: ['data-variant', 'data-size', 'data-invalid', 'data-disabled', 'data-readonly'],
    children: [
      { slot: 'iconLeft', ariaAttributes: ['aria-hidden'] },
      { slot: 'input', ariaAttributes: ['aria-valuemin', 'aria-valuemax', 'aria-valuenow'] },
      {
        slot: 'controls',
        children: [
          { slot: 'increment', ariaAttributes: ['aria-label'] },
          { slot: 'decrement', ariaAttributes: ['aria-label'] },
        ],
      },
    ],
  },

  controlled: 'value' as const,
  controlledProps: {
    valueProp: 'value',
    defaultValueProp: 'defaultValue',
    onChangeProp: 'onValueChange',
  },
  keyboard: 'linear' as const,
  focus: 'delegated' as const,
  formType: 'native-name' as const,
  asChild: false,

  animations: [],

  renderContracts: [
    { id: 'root-click-focuses-input', description: 'Clicking anywhere on the root wrapper focuses the input element' },
    { id: 'input-type-text', description: 'Input type is "text" with inputMode="decimal" and role="spinbutton" for native numeric keyboard on mobile' },
    { id: 'hook-manages-state', description: 'useNumberInput hook manages controlled/uncontrolled state, filtering, clamping, formatting, and step logic' },
    { id: 'hold-to-repeat', description: 'Increment/decrement buttons support hold-to-repeat via pointerDown + setTimeout(300ms) + setInterval(50ms)' },
    { id: 'controls-hidden-readonly', description: 'Controls are hidden when readOnly=true via CSS display:none' },
    { id: 'controls-hidden-prop', description: 'Controls are hidden when hideControls=true (not rendered)' },
    { id: 'stepper-buttons-tabindex', description: 'Stepper buttons have tabIndex=-1 to keep them out of tab order' },
    { id: 'stepper-buttons-prevent-default', description: 'Stepper buttons call preventDefault on pointerDown to prevent focus stealing' },
    { id: 'icon-size-scales', description: 'Chevron icon size scales with component size: sm=12, md=14, lg=16' },
    { id: 'input-filters-chars', description: 'Hook filters input to allow only digits, one minus at start (if allowNegative), and one decimal (if allowDecimal)' },
    { id: 'blur-clamp-format', description: 'On blur, hook clamps value to min/max (if clampBehavior=blur) and reformats with decimalScale/formatValue' },
    { id: 'shift-step-multiplier', description: 'Holding Shift during ArrowUp/Down or button hold uses shiftStep (defaults to step*10)' },
    { id: 'prefix-suffix-display', description: 'Prefix and suffix are prepended/appended to display value but stripped during editing' },
    { id: 'ref-forwards-to-root', description: 'Component ref forwards to the root div element' },
  ],

  tokens: [
    { name: '--move-numberinput-bg', value: 'var(--move-bg-subtle)', description: 'Root background color' },
    { name: '--move-numberinput-border', value: 'var(--move-border-base)', description: 'Root border color' },
    { name: '--move-numberinput-border-hover', value: 'var(--move-border-emphasis)', description: 'Root hover border color' },
    { name: '--move-numberinput-border-focus', value: 'var(--move-primary)', description: 'Root focus border color' },
    { name: '--move-numberinput-radius', value: 'var(--move-rounded-md)', description: 'Root border radius' },
    { name: '--move-numberinput-padding-x', value: 'var(--move-spacing-sm)', description: 'Root horizontal padding' },
    { name: '--move-numberinput-padding-y', value: 'var(--move-spacing-xs)', description: 'Root vertical padding' },
    { name: '--move-numberinput-font-size', value: 'inherit', description: 'Input font size (inherits, overridden by size)' },
    { name: '--move-numberinput-fg', value: 'var(--move-fg-base)', description: 'Input text color' },
    { name: '--move-numberinput-placeholder', value: 'var(--move-fg-muted)', description: 'Placeholder text color' },
    { name: '--move-numberinput-height', value: 'var(--move-control-height-md)', description: 'Root height' },
    { name: '--move-numberinput-icon-color', value: 'var(--move-fg-muted)', description: 'Icon and stepper button color' },
    { name: '--move-numberinput-icon-gap', value: 'var(--move-spacing-sm)', description: 'Gap between icon, input, and controls' },
  ],

  variants: {
    variant: ['outlined', 'filled'] as string[],
  },
  sizes: ['sm', 'md', 'lg'] as string[],

  labels: [
    { key: 'increment', default: 'Increment', description: 'Aria label for increment button' },
    { key: 'decrement', default: 'Decrement', description: 'Aria label for decrement button' },
  ],

  hasHook: true,
  engineImports: ['withMoveComponent'] as string[],

  componentDeps: [] as string[],

  testing: {
    behaviors: [
      'Renders root div with input, optional left icon, and stepper controls',
      'Input has type=text, inputMode=decimal, role=spinbutton',
      'Input displays formatted numeric value via useNumberInput hook',
      'Controlled value via value prop',
      'Uncontrolled value via defaultValue prop',
      'onValueChange fires with numeric value and display string',
      'Increment button increases value by step',
      'Decrement button decreases value by step',
      'Shift+increment uses shiftStep (defaults to step*10)',
      'Hold-to-repeat on stepper buttons (300ms delay, 50ms interval)',
      'Stepper buttons have tabIndex=-1',
      'Input filters non-numeric characters',
      'Input allows minus at start when allowNegative=true',
      'Input blocks minus when allowNegative=false',
      'Input allows decimal point when allowDecimal=true',
      'Input blocks decimal when allowDecimal=false',
      'clampBehavior=blur clamps on blur',
      'clampBehavior=strict clamps immediately on input',
      'clampBehavior=none never clamps',
      'decimalScale limits displayed decimal places',
      'prefix prepended to display value',
      'suffix appended to display value',
      'formatValue/parseValue custom formatter and parser',
      'hideControls=true hides stepper buttons',
      'readOnly hides controls via CSS',
      'Defaults variant=outlined, size=md, step=1, clampBehavior=blur',
      'Applies data-variant, data-size, data-invalid, data-disabled, data-readonly',
      'Root click focuses input',
      'Custom width prop applied',
      'iconLeft renders with aria-hidden',
      'Chevron icons scale with size (sm=12, md=14, lg=16)',
      'Forwards className and style on root',
      'Size sm: smaller height, font-size, padding',
      'Size lg: larger height, font-size, padding',
      'Filled variant changes background and hides border',
      'Invalid state shows error border',
      'Disabled state reduces opacity',
    ],
    keyboard: [
      'ArrowUp increments value',
      'ArrowDown decrements value',
      'Shift+ArrowUp increments by shiftStep',
      'Shift+ArrowDown decrements by shiftStep',
      'ArrowUp/Down prevented when disabled or readOnly',
    ] as string[],
    aria: [
      'Input has role=spinbutton',
      'Input has aria-valuemin when min provided',
      'Input has aria-valuemax when max provided',
      'Input has aria-valuenow with current numeric value',
      'Increment button has aria-label "Increment"',
      'Decrement button has aria-label "Decrement"',
      'Left icon has aria-hidden=true',
    ] as string[],
    form: [
      'Input participates in form submission via name prop',
      'Input supports required attribute',
    ] as string[],
  },

  iconsUsed: ['chevron-down', 'chevron-up'],
  defaultReview: {
    status: 'approved' as const,
    decisionSource: 'accept-all' as const,
    overrides: {},
  },
} satisfies ComponentSpec;
