/**
 * Search synonyms keyed by component slug. The components overview matches a
 * query against a component's name, tagline, category AND these aliases — so
 * "modal" finds Dialog, "spinner" finds Loader, "otp" finds PinInput, etc.
 * Extend freely; components without an entry just match on name/tagline.
 */
export const SEARCH_ALIASES: Record<string, string[]> = {
  accordion: ['collapse', 'expander', 'disclosure', 'faq'],
  alert: ['banner', 'callout', 'notice', 'notification'],
  align: ['layout', 'flex', 'row', 'justify', 'distribute'],
  'audio-player': ['media', 'player', 'sound', 'podcast', 'mp3'],
  autocomplete: ['combobox', 'typeahead', 'search select', 'suggest'],
  avatar: ['profile picture', 'user image', 'gravatar', 'initials'],
  badge: ['tag', 'chip', 'pill', 'label', 'status'],
  breadcrumb: ['path', 'trail', 'navigation'],
  button: ['btn', 'cta', 'action'],
  calendar: ['datepicker', 'date', 'month', 'schedule'],
  'calendar-view': ['agenda', 'schedule', 'events', 'week view', 'month view'],
  card: ['panel', 'tile', 'surface'],
  carousel: ['slider', 'gallery', 'slideshow', 'swiper'],
  'chat-bubble': ['message', 'speech bubble', 'conversation', 'im'],
  checkbox: ['check', 'tickbox', 'tick'],
  code: ['codeblock', 'snippet', 'syntax', 'monospace'],
  collapsible: ['accordion', 'expander', 'disclosure', 'show more'],
  'color-input': ['color', 'colour', 'swatch', 'hex'],
  'color-picker': ['color', 'colour', 'swatch', 'hsl', 'rgb', 'eyedropper'],
  'date-picker': ['calendar', 'datepicker', 'date', 'schedule'],
  dialog: ['modal', 'popup', 'lightbox', 'overlay'],
  divider: ['separator', 'rule', 'hr', 'line'],
  drawer: ['sheet', 'off-canvas', 'side panel', 'slide-over'],
  dropdown: ['menu', 'context menu', 'actions', 'overflow'],
  'empty-state': ['placeholder', 'no data', 'zero state', 'blank'],
  'file-upload': ['dropzone', 'attach', 'upload', 'file picker', 'drag and drop'],
  'form-field': ['field', 'label', 'form', 'input wrapper'],
  grid: ['layout', 'columns', 'masonry'],
  heading: ['title', 'header', 'h1', 'h2'],
  image: ['picture', 'img', 'photo'],
  'image-group': ['gallery', 'photos', 'thumbnails'],
  'input-range': ['slider', 'range', 'track'],
  'input-text': ['textfield', 'textbox', 'input', 'field'],
  link: ['anchor', 'hyperlink', 'href'],
  list: ['listview', 'items', 'ul'],
  loader: ['spinner', 'loading', 'busy', 'progress'],
  'number-input': ['stepper', 'numeric', 'quantity', 'spinbutton'],
  pagination: ['pager', 'paging', 'pages', 'next previous'],
  password: ['secret', 'masked input'],
  'pin-input': ['otp', 'code', 'verification', 'one-time', '2fa', 'mfa'],
  popover: ['popup', 'flyout', 'overlay', 'hint'],
  'progress-bar': ['progress', 'loading bar', 'meter', 'percent'],
  'radio-group': ['radio', 'options', 'choices', 'single select'],
  'rich-text-editor': ['wysiwyg', 'editor', 'formatting', 'prose'],
  'scroll-area': ['scrollbar', 'overflow', 'scroller'],
  select: ['dropdown', 'combobox', 'picker', 'options'],
  skeleton: ['placeholder', 'shimmer', 'loading', 'ghost'],
  slider: ['range', 'track', 'thumb'],
  splitter: ['split pane', 'resizable', 'panes', 'divider'],
  switch: ['toggle', 'on off'],
  table: ['grid', 'datagrid', 'datatable', 'rows', 'spreadsheet'],
  'table-of-contents': ['toc', 'on this page', 'outline', 'anchors'],
  tabs: ['tabbar', 'segmented', 'sections'],
  textarea: ['multiline', 'text area', 'input', 'comment'],
  'time-field': ['time', 'clock', 'hour minute'],
  timeline: ['activity', 'feed', 'history', 'steps'],
  toast: ['notification', 'snackbar', 'alert', 'flash'],
  'toggle-button': ['toggle', 'pressed', 'switch'],
  'toggle-group': ['segmented', 'toggle', 'button group'],
  tooltip: ['hint', 'popup', 'title'],
  'video-player': ['media', 'player', 'video', 'mp4', 'stream'],
};
