// TimeField.spec.ts — Component specification
// specHash: PLACEHOLDER

import type { ComponentSpec } from '../../../spec-type';

export const spec = {
  schemaVersion: 7 as const,
  name: 'TimeField',
  componentClass: 'input_plain' as const,
  category: 'form',
  description: 'Time input with individual hour/minute/second segments, optional 12h/24h cycle, and dropdown column picker',

  synonyms: ['time input', 'clock input', 'time picker', 'hour minute'],
  families: {
    behavior:  ["form-input"],
    state:     ["controlled-value"],
    animation: ["none"],
    a11y:      ["none"],
  },

  compound: true,
  rootElement: 'div',
  slots: [
    { name: 'root', element: 'div', description: 'Outer wrapper with input-like styling, anchors dropdown popover' },
    { name: 'segment', element: 'input', description: 'Individual time segment input (hour, minute, second) with spinbutton role' },
    { name: 'separator', element: 'span', description: 'Colon separator between segments' },
    { name: 'period', element: 'button', description: 'AM/PM toggle button for 12h mode' },
    { name: 'dropdown', element: 'div', description: 'Radix Popover.Content dropdown with scrollable columns' },
    { name: 'dropdownColumn', element: 'div', description: 'Scrollable column of selectable time values' },
  ],

  subComponents: [
    {
      name: 'Root',
      slots: [{ name: 'root', element: 'div', description: 'Outer wrapper' }],
      props: [
        { name: 'children', type: 'React.ReactNode', moveSpecific: false, description: 'Custom segment layout or auto-rendered segments' },
        { name: 'className', type: 'string', moveSpecific: false, description: 'CSS class name' },
        { name: 'style', type: 'React.CSSProperties', moveSpecific: false, description: 'Inline styles' },
        { name: 'value', type: 'string', moveSpecific: true, description: 'Controlled time value in 24h format (HH, HH:mm, HH:mm:ss)' },
        { name: 'defaultValue', type: 'string', moveSpecific: true, description: 'Default time value (uncontrolled)' },
        { name: 'onValueChange', type: '(value: string) => void', moveSpecific: true, description: 'Called when time value changes' },
        { name: 'granularity', type: "'hour' | 'minute' | 'second'", default: "'minute'", moveSpecific: true, description: 'Which segments to show' },
        { name: 'hourCycle', type: '12 | 24', default: '24', moveSpecific: true, description: '12 or 24 hour display cycle' },
        { name: 'withDropdown', type: 'boolean', default: 'false', moveSpecific: true, description: 'Show dropdown column picker on ArrowDown' },
        { name: 'animations', type: 'AnimationTrigger[] | false', moveSpecific: true, description: 'Animation config for dropdown enter/exit' },
        { name: 'size', typeRef: 'Size', default: "'md'", moveSpecific: true, description: 'Input size' },
        { name: 'disabled', type: 'boolean', default: 'false', moveSpecific: true, description: 'Disabled state' },
        { name: 'invalid', type: 'boolean', default: 'false', moveSpecific: true, description: 'Invalid state' },
        { name: 'min', type: 'string', moveSpecific: true, description: 'Minimum time constraint (24h format)' },
        { name: 'max', type: 'string', moveSpecific: true, description: 'Maximum time constraint (24h format)' },
        { name: 'step', type: 'number', default: '1', moveSpecific: true, description: 'Arrow key increment in seconds' },
        { name: 'labels', type: 'Partial<TimeFieldLabels>', moveSpecific: true, description: 'Override aria-label strings for segments and period' },
      ],
      usesFactory: false,
      description: 'Stateful root that provides TimeFieldContext, renders segments auto or via children, optionally wraps in Radix Popover for dropdown mode',
    },
    {
      name: 'Segment',
      slots: [{ name: 'segment', element: 'input', description: 'Time segment input' }],
      props: [
        { name: 'segment', type: "SegmentType", moveSpecific: true, description: 'Which segment this renders (hour, minute, second)' },
        { name: 'className', type: 'string', moveSpecific: false, description: 'CSS class name' },
        { name: 'style', type: 'React.CSSProperties', moveSpecific: false, description: 'Inline styles' },
      ],
      usesFactory: true,
      description: 'Individual segment input with spinbutton role, digit typing with auto-advance, and arrow key increment/decrement',
    },
    {
      name: 'Separator',
      slots: [{ name: 'separator', element: 'span', description: 'Colon separator' }],
      props: [
        { name: 'className', type: 'string', moveSpecific: false, description: 'CSS class name' },
        { name: 'style', type: 'React.CSSProperties', moveSpecific: false, description: 'Inline styles' },
        { name: 'children', type: 'React.ReactNode', default: "':'", moveSpecific: false, description: 'Separator content' },
      ],
      usesFactory: true,
      description: 'Visual separator between segments, defaults to colon, has aria-hidden',
    },
    {
      name: 'Period',
      slots: [{ name: 'period', element: 'button', description: 'AM/PM toggle' }],
      props: [
        { name: 'className', type: 'string', moveSpecific: false, description: 'CSS class name' },
        { name: 'style', type: 'React.CSSProperties', moveSpecific: false, description: 'Inline styles' },
      ],
      usesFactory: true,
      description: 'AM/PM toggle button with spinbutton role, responds to ArrowUp/Down and A/P key typing',
    },
    {
      name: 'Dropdown',
      slots: [{ name: 'dropdown', element: 'div', description: 'Dropdown popover' }],
      props: [
        { name: 'children', type: 'React.ReactNode', moveSpecific: false, description: 'DropdownColumn elements' },
        { name: 'className', type: 'string', moveSpecific: false, description: 'CSS class name' },
        { name: 'style', type: 'React.CSSProperties', moveSpecific: false, description: 'Inline styles' },
      ],
      usesFactory: false,
      description: 'Animated Radix Popover.Content containing scrollable columns for time selection',
    },
    {
      name: 'DropdownColumn',
      slots: [{ name: 'dropdownColumn', element: 'div', description: 'Scrollable column' }],
      props: [
        { name: 'segment', type: "SegmentType | 'period'", moveSpecific: true, description: 'Which segment this column represents' },
        { name: 'className', type: 'string', moveSpecific: false, description: 'CSS class name' },
        { name: 'style', type: 'React.CSSProperties', moveSpecific: false, description: 'Inline styles' },
      ],
      usesFactory: true,
      description: 'Scrollable column of selectable values for a time segment, auto-scrolls to selected on open',
    },
  ],

  props: [
    { name: 'value', type: 'string', moveSpecific: true, description: 'Controlled time value' },
    { name: 'defaultValue', type: 'string', moveSpecific: true, description: 'Default time value' },
    { name: 'onValueChange', type: '(value: string) => void', moveSpecific: true, description: 'Value change handler' },
    { name: 'granularity', type: "'hour' | 'minute' | 'second'", default: "'minute'", moveSpecific: true, description: 'Visible segments' },
    { name: 'hourCycle', type: '12 | 24', default: '24', moveSpecific: true, description: 'Hour display cycle' },
    { name: 'withDropdown', type: 'boolean', default: 'false', moveSpecific: true, description: 'Enable dropdown picker' },
    { name: 'animations', type: 'AnimationTrigger[] | false', moveSpecific: true, description: 'Dropdown animation config' },
    { name: 'size', typeRef: 'Size', default: "'md'", moveSpecific: true, description: 'Input size' },
    { name: 'disabled', type: 'boolean', default: 'false', moveSpecific: true, description: 'Disabled state' },
    { name: 'invalid', type: 'boolean', default: 'false', moveSpecific: true, description: 'Invalid state' },
    { name: 'min', type: 'string', moveSpecific: true, description: 'Min time constraint' },
    { name: 'max', type: 'string', moveSpecific: true, description: 'Max time constraint' },
    { name: 'step', type: 'number', default: '1', moveSpecific: true, description: 'Increment step' },
    { name: 'labels', type: 'Partial<TimeFieldLabels>', moveSpecific: true, description: 'Override aria-label strings for segments and period' },
    { name: 'children', type: 'React.ReactNode', moveSpecific: false, description: 'Custom segment layout' },
    { name: 'className', type: 'string', moveSpecific: false, description: 'CSS class name' },
    { name: 'style', type: 'React.CSSProperties', moveSpecific: false, description: 'Inline styles' },
  ],

  anatomy: {
    slot: 'root',
    dataAttributes: ['data-size', 'data-granularity', 'data-hourcycle', 'data-disabled', 'data-invalid'],
    children: [
      { slot: 'segment', dataAttributes: ['data-segment'] },
      { slot: 'separator' },
      { slot: 'period', dataAttributes: ['data-segment'] },
      {
        slot: 'dropdown',
        children: [
          { slot: 'dropdownColumn', dataAttributes: ['data-segment'] },
        ],
      },
    ],
  },

  controlled: 'value' as const,
  controlledProps: {
    valueProp: 'value',
    defaultValueProp: 'defaultValue',
    onChangeProp: 'onValueChange',
  },

  keyboard: 'linear' as const,
  focus: 'roving' as const,
  formType: null,
  asChild: false,

  renderContracts: [
    { id: 'root-provides-context', description: 'Root provides TimeFieldContext with useTimeField return, segment refs, focus navigation, dropdown state, and animation config' },
    { id: 'auto-render-segments', description: 'When no children provided, Root auto-renders segments based on granularity and hourCycle with separators between numeric segments' },
    { id: 'dropdown-mode-wraps-popover', description: 'When withDropdown=true, Root wraps in Radix Popover.Root with Anchor on the root element' },
    { id: 'dropdown-auto-columns', description: 'When withDropdown=true, Root auto-renders DropdownColumn for each segment plus period (if 12h)' },
    { id: 'segment-registers-ref', description: 'Each Segment registers its DOM ref in segmentRefs map for focus management' },
    { id: 'segment-digit-typing', description: 'Segment handles digit typing with two-digit buffering and auto-advance to next segment when full' },
    { id: 'segment-arrow-direction-flip', description: 'When dropdown is open, ArrowUp decrements and ArrowDown increments (flipped from closed behavior)' },
    { id: 'period-typing', description: 'Period responds to A key for AM and P key for PM' },
    { id: 'dropdown-scroll-to-selected', description: 'DropdownColumn scrolls selected item into view on open using requestAnimationFrame' },
    { id: 'dropdown-item-click', description: 'DropdownColumn item click sets the corresponding segment value (handles 12h/24h conversion for hours)' },
    { id: 'value-always-24h', description: 'Internal value is always stored in 24h format regardless of hourCycle display setting' },
    { id: 'segment-focus-navigation', description: 'ArrowRight/Tab advances to next segment, ArrowLeft/Shift+Tab goes to previous segment' },
  ],

  animations: [
    { trigger: 'Content.enter', sequence: [[
      { fn: 'animateDimension', animation: { height: { ease: 'poppy' } } },
      { children: '[role="option"]', animation: { scale: { from: 0.8, to: 1, ease: 'poppy' }, opacity: { from: 0, to: 1 } }, stagger: { delay: 30 } },
    ]] },
    { trigger: 'Content.exit', sequence: [[
      { fn: 'animateDimension', animation: { height: { ease: 'snappy' } } },
      { children: '[role="option"]', animation: { scale: { to: 0.8, ease: 'snappy' }, opacity: { to: 0 } }, stagger: { delay: 20, from: 'last' } },
    ]] },
  ],

  tokens: [
    // Root tokens
    { name: '--move-timefield-bg', value: 'var(--move-bg-subtle)', description: 'Root background color' },
    { name: '--move-timefield-border', value: 'var(--move-border-base)', description: 'Root border color' },
    { name: '--move-timefield-border-hover', value: 'var(--move-border-emphasis)', description: 'Root border color on hover' },
    { name: '--move-timefield-border-focus', value: 'var(--move-primary)', description: 'Root border color on focus-within' },
    { name: '--move-timefield-radius', value: 'var(--move-rounded-md)', description: 'Root border radius' },
    { name: '--move-timefield-padding-x', value: 'var(--move-spacing-sm)', description: 'Root horizontal padding' },
    { name: '--move-timefield-padding-y', value: 'var(--move-spacing-xs)', description: 'Root vertical padding' },
    { name: '--move-timefield-fg', value: 'var(--move-fg-base)', description: 'Segment text color' },
    { name: '--move-timefield-placeholder', value: 'var(--move-fg-muted)', description: 'Separator text color' },
    { name: '--move-timefield-height', value: 'var(--move-control-height-md)', description: 'Root height' },
    // Dropdown tokens
    { name: '--move-timefield-dropdown-bg', value: 'var(--move-bg-subtle)', description: 'Dropdown background' },
    { name: '--move-timefield-dropdown-border', value: 'var(--move-border-base)', description: 'Dropdown border color' },
    { name: '--move-timefield-dropdown-radius', value: 'var(--move-rounded-lg)', description: 'Dropdown border radius' },
    { name: '--move-timefield-dropdown-shadow', value: 'var(--move-shadow-overlay)', description: 'Dropdown box shadow' },
    { name: '--move-timefield-dropdown-padding', value: 'var(--move-spacing-xs)', description: 'Dropdown padding' },
  ],

  variants: {},
  sizes: ['sm', 'md', 'lg'] as string[],

  labels: [
    { key: 'hour', default: 'hour', description: 'aria-label for the hour segment' },
    { key: 'minute', default: 'minute', description: 'aria-label for the minute segment' },
    { key: 'second', default: 'second', description: 'aria-label for the second segment' },
    { key: 'period', default: 'period', description: 'aria-label for the AM/PM period toggle' },
  ] as { key: string; default: string; description: string }[],

  childrenKind: 'composition' as const,
  propRoles: {
    value: 'behavior' as const,
    defaultValue: 'behavior' as const,
    granularity: 'behavior' as const,
    hourCycle: 'behavior' as const,
    withDropdown: 'behavior' as const,
    animations: 'behavior' as const,
    disabled: 'behavior' as const,
    invalid: 'behavior' as const,
    min: 'behavior' as const,
    max: 'behavior' as const,
    step: 'behavior' as const,
    children: 'composition' as const,
  },

  hasHook: true,
  engineImports: ['withMoveComponent', 'useMergedRef'] as string[],
  radixPrimitive: 'Popover',
  componentDeps: [] as string[],

  testing: {
    behaviors: [
      'Root provides TimeFieldContext to children',
      'Root auto-renders segments when no children provided',
      'Root renders hour+minute segments for granularity="minute"',
      'Root renders hour+minute+second segments for granularity="second"',
      'Root renders hour-only segment for granularity="hour"',
      'Root renders Period button for hourCycle=12',
      'Root renders separators between numeric segments',
      'Root wraps in Radix Popover when withDropdown=true',
      'Segment registers ref in segmentRefs map',
      'Segment shows zero-padded value from useTimeField',
      'Segment digit typing buffers and auto-advances on two digits',
      'Segment single digit auto-commits when value exceeds max first digit',
      'Segment ArrowUp increments value, wrapping at boundary',
      'Segment ArrowDown decrements value, wrapping at boundary',
      'Segment clearBuffer on focus for fresh typing',
      'Period toggles AM/PM on ArrowUp/ArrowDown',
      'Period responds to A and P key typing',
      'Dropdown renders DropdownColumn for each segment',
      'DropdownColumn generates correct items (24h=0-23, 12h=1-12, min/sec=0-59)',
      'DropdownColumn scrolls to selected on open',
      'DropdownColumn item click sets segment value',
      'DropdownColumn handles 12h/24h conversion on hour click',
      'Disabled state prevents all interaction',
      'Invalid state applies error border styling',
      'Size data-attribute controls height and font size via CSS',
    ],
    keyboard: [
      'ArrowUp increments focused segment',
      'ArrowDown decrements focused segment (opens dropdown if withDropdown)',
      'ArrowRight advances focus to next segment',
      'ArrowLeft moves focus to previous segment',
      'Tab advances to next segment (passes through if last)',
      'Shift+Tab moves to previous segment (passes through if first)',
      'Digit keys type into segment with buffered auto-advance',
      'Backspace/Delete clears typing buffer',
      'Period: A sets AM, P sets PM',
      'When dropdown open: ArrowUp decrements, ArrowDown increments (flipped)',
      'Escape closes dropdown',
    ],
    aria: [
      'Segment has role="spinbutton"',
      'Segment has aria-label matching segment type',
      'Segment has aria-valuenow with numeric value',
      'Period has role="spinbutton"',
      'Period has aria-label="period"',
      'Period has aria-valuenow (0=AM, 1=PM)',
      'Separator has aria-hidden="true"',
    ],
    animation: [
      'Dropdown uses animateDimension with stagger for enter/exit',
      'Enter: opacity [0,1] + scale [0.5,1] with outQuart easing',
      'Exit: opacity [1,0] + scale [1,0.95] with outQuart easing, 200ms',
      'Stagger: items via button selector with 30ms delay',
      'animations={false} disables dropdown animation',
    ],
  },

  defaultReview: {
    status: 'approved' as const,
    decisionSource: 'accept-all' as const,
    overrides: {},
  },
} satisfies ComponentSpec;
