// Drawer.spec.ts — Component specification
// specHash: PLACEHOLDER

export const spec = {
  schemaVersion: 7 as const,
  name: 'Drawer',
  componentClass: 'overlay_layer' as const,
  category: 'overlay',
  description: 'Slide-in panel from any edge with overlay backdrop, responsive auto-switching to bottom sheet on mobile, and structured header/body/footer layout',

  compound: true,
  rootElement: 'div',
  slots: [
    { name: 'trigger', element: 'RadixDialog.Trigger', description: 'Button that opens the drawer' },
    { name: 'overlay', element: 'RadixDialog.Overlay', description: 'Backdrop overlay behind the drawer' },
    { name: 'content', element: 'RadixDialog.Content', description: 'Slide-in drawer panel' },
    { name: 'header', element: 'div', description: 'Top section containing title and close button' },
    { name: 'body', element: 'div', description: 'Scrollable content area' },
    { name: 'footer', element: 'div', description: 'Bottom section for actions' },
    { name: 'title', element: 'RadixDialog.Title', description: 'Heading element for the drawer title' },
    { name: 'description', element: 'RadixDialog.Description', description: 'Paragraph element for the drawer description' },
    { name: 'close', element: 'RadixDialog.Close', description: 'Button that triggers animated close' },
    { name: 'handle', element: 'div', description: 'Drag handle indicator shown in bottom-sheet mode' },
  ],

  subComponents: [
    {
      name: 'Root',
      slots: [],
      props: [
        { name: 'children', type: 'React.ReactNode', moveSpecific: false, description: 'Drawer sub-components' },
        { name: 'open', type: 'boolean', moveSpecific: false, description: 'Controlled open state' },
        { name: 'defaultOpen', type: 'boolean', moveSpecific: false, description: 'Initial open state (uncontrolled)' },
        { name: 'onOpenChange', type: '(open: boolean) => void', moveSpecific: false, description: 'Called when open state changes' },
        { name: 'animations', type: 'AnimationTrigger[] | false', moveSpecific: true, description: 'Animation config or false to disable' },
        { name: 'modal', type: 'boolean', default: 'true', moveSpecific: false, description: 'Whether to render as modal with backdrop' },
      ],
      usesFactory: false,
      description: 'Stateful root that manages open/close state, animation context, and close-after-exit-animation coordination',
    },
    {
      name: 'Trigger',
      slots: [{ name: 'trigger', element: 'RadixDialog.Trigger', description: 'Trigger button element' }],
      props: [
        { name: 'className', type: 'string', moveSpecific: false, description: 'CSS class name' },
        { name: 'style', type: 'React.CSSProperties', moveSpecific: false, description: 'Inline styles' },
        { name: 'children', type: 'React.ReactNode', moveSpecific: false, description: 'Trigger content' },
        { name: 'asChild', type: 'boolean', moveSpecific: true, description: 'Merge props onto child element instead of wrapping' },
      ],
      usesFactory: true,
      radixPrimitive: 'Dialog.Trigger',
      description: 'Element that opens the drawer when clicked',
    },
    {
      name: 'Portal',
      slots: [],
      props: [
        { name: 'children', type: 'React.ReactNode', moveSpecific: false, description: 'Portal content' },
        { name: 'container', type: 'HTMLElement', moveSpecific: false, description: 'Custom portal mount target' },
      ],
      usesFactory: false,
      description: 'Portals drawer content to document body (or custom container)',
    },
    {
      name: 'Overlay',
      slots: [{ name: 'overlay', element: 'RadixDialog.Overlay', description: 'Backdrop element' }],
      props: [
        { name: 'className', type: 'string', moveSpecific: false, description: 'CSS class name' },
        { name: 'style', type: 'React.CSSProperties', moveSpecific: false, description: 'Inline styles' },
      ],
      usesFactory: true,
      radixPrimitive: 'Dialog.Overlay',
      description: 'Full-screen backdrop behind the drawer with fade in/out animation',
    },
    {
      name: 'Content',
      slots: [{ name: 'content', element: 'RadixDialog.Content', description: 'Drawer content panel' }],
      props: [
        { name: 'className', type: 'string', moveSpecific: false, description: 'CSS class name' },
        { name: 'style', type: 'React.CSSProperties', moveSpecific: false, description: 'Inline styles' },
        { name: 'children', type: 'React.ReactNode', moveSpecific: false, description: 'Drawer body content' },
        { name: 'position', type: "'left' | 'right' | 'top' | 'bottom'", default: "'right'", moveSpecific: true, description: 'Edge the drawer slides in from' },
        { name: 'size', type: "'xs' | 'sm' | 'md' | 'lg' | 'xl' | 'full'", default: "'md'", moveSpecific: true, description: 'Drawer width (left/right) or height (top/bottom)' },
        { name: 'responsive', type: 'boolean', default: 'true', moveSpecific: true, description: 'Auto-switch to bottom sheet on mobile viewport' },
        { name: 'breakpoint', type: 'number', default: '768', moveSpecific: true, description: 'Viewport width below which responsive mode activates (px)' },
        { name: 'onOpenAutoFocus', type: '(event: Event) => void', moveSpecific: false, description: 'Called when content receives auto focus on open' },
        { name: 'onPointerDownOutside', type: '(event: Event) => void', moveSpecific: false, description: 'Called when pointer down outside content' },
        { name: 'onEscapeKeyDown', type: '(event: KeyboardEvent) => void', moveSpecific: false, description: 'Called when escape key pressed' },
        { name: 'onInteractOutside', type: '(event: Event) => void', moveSpecific: false, description: 'Called on any outside interaction' },
      ],
      usesFactory: true,
      radixPrimitive: 'Dialog.Content',
      description: 'Slide-in panel with position variants, responsive bottom-sheet mode, and exit animation coordination',
    },
    {
      name: 'Header',
      slots: [{ name: 'header', element: 'div', description: 'Header container' }],
      props: [
        { name: 'className', type: 'string', moveSpecific: false, description: 'CSS class name' },
        { name: 'style', type: 'React.CSSProperties', moveSpecific: false, description: 'Inline styles' },
        { name: 'children', type: 'React.ReactNode', moveSpecific: false, description: 'Header content (typically Title + Close)' },
      ],
      usesFactory: true,
      description: 'Top section with flex layout for title and close button',
    },
    {
      name: 'Body',
      slots: [{ name: 'body', element: 'div', description: 'Body container' }],
      props: [
        { name: 'className', type: 'string', moveSpecific: false, description: 'CSS class name' },
        { name: 'style', type: 'React.CSSProperties', moveSpecific: false, description: 'Inline styles' },
        { name: 'children', type: 'React.ReactNode', moveSpecific: false, description: 'Scrollable body content' },
      ],
      usesFactory: true,
      description: 'Scrollable content area (flex: 1, overflow: auto)',
    },
    {
      name: 'Footer',
      slots: [{ name: 'footer', element: 'div', description: 'Footer container' }],
      props: [
        { name: 'className', type: 'string', moveSpecific: false, description: 'CSS class name' },
        { name: 'style', type: 'React.CSSProperties', moveSpecific: false, description: 'Inline styles' },
        { name: 'children', type: 'React.ReactNode', moveSpecific: false, description: 'Footer content (typically action buttons)' },
      ],
      usesFactory: true,
      description: 'Bottom action bar with flex layout',
    },
    {
      name: 'Title',
      slots: [{ name: 'title', element: 'RadixDialog.Title', description: 'Title heading' }],
      props: [
        { name: 'className', type: 'string', moveSpecific: false, description: 'CSS class name' },
        { name: 'style', type: 'React.CSSProperties', moveSpecific: false, description: 'Inline styles' },
        { name: 'children', type: 'React.ReactNode', moveSpecific: false, description: 'Title text' },
      ],
      usesFactory: true,
      radixPrimitive: 'Dialog.Title',
      description: 'Accessible drawer title rendered as heading element',
    },
    {
      name: 'Description',
      slots: [{ name: 'description', element: 'RadixDialog.Description', description: 'Description paragraph' }],
      props: [
        { name: 'className', type: 'string', moveSpecific: false, description: 'CSS class name' },
        { name: 'style', type: 'React.CSSProperties', moveSpecific: false, description: 'Inline styles' },
        { name: 'children', type: 'React.ReactNode', moveSpecific: false, description: 'Description text' },
      ],
      usesFactory: true,
      radixPrimitive: 'Dialog.Description',
      description: 'Accessible drawer description rendered as paragraph',
    },
    {
      name: 'Close',
      slots: [{ name: 'close', element: 'RadixDialog.Close', description: 'Close button' }],
      props: [
        { name: 'className', type: 'string', moveSpecific: false, description: 'CSS class name' },
        { name: 'style', type: 'React.CSSProperties', moveSpecific: false, description: 'Inline styles' },
        { name: 'children', type: 'React.ReactNode', moveSpecific: false, description: 'Close button content' },
        { name: 'asChild', type: 'boolean', moveSpecific: true, description: 'Merge props onto child element instead of wrapping' },
      ],
      usesFactory: true,
      radixPrimitive: 'Dialog.Close',
      description: 'Button that triggers animated close via context (does not immediately unmount)',
    },
    {
      name: 'Handle',
      slots: [{ name: 'handle', element: 'div', description: 'Drag handle bar' }],
      props: [
        { name: 'className', type: 'string', moveSpecific: false, description: 'CSS class name' },
        { name: 'style', type: 'React.CSSProperties', moveSpecific: false, description: 'Inline styles' },
      ],
      usesFactory: true,
      description: 'Visual drag handle indicator, auto-shown in bottom-sheet mode',
    },
  ],

  props: [],

  anatomy: {
    slot: 'overlay',
    children: [
      {
        slot: 'content',
        dataAttributes: ['data-position', 'data-size', 'data-responsive'],
        children: [
          { slot: 'handle' },
          {
            slot: 'header',
            children: [
              { slot: 'title' },
              { slot: 'close' },
            ],
          },
          { slot: 'description' },
          { slot: 'body' },
          { slot: 'footer' },
        ],
      },
    ],
  },

  controlled: 'open' as const,
  controlledProps: {
    valueProp: 'open',
    defaultValueProp: 'defaultOpen',
    onChangeProp: 'onOpenChange',
  },
  keyboard: null,
  focus: 'trap' as const,
  formType: null,
  asChild: true,

  dismissBehavior: 'unmountAfterExit' as const,

  surface: {
    slot: 'content',
    level: 'subtle' as const,
  },

  animations: [
    { trigger: 'Overlay.enter', sequence: [{ animation: { opacity: { from: 0, to: 1, duration: 200 } } }] },
    { trigger: 'Overlay.exit', sequence: [{ animation: { opacity: { to: 0, duration: 150 } } }] },
    {
      trigger: 'Content.enter',
      sequence: [{ animation: { translateX: { from: '100%', to: '0%', ease: 'sidebar' } } }],
      note: 'Default for position=right. Position variants: left=-100%→0%, top=translateY -100%→0%, bottom=translateY 100%→0%',
    },
    {
      trigger: 'Content.exit',
      sequence: [{ animation: { translateX: { to: '100%', ease: 'snappy' } } }],
      note: 'Mirrors enter direction. Position variants adjust axis and direction.',
    },
  ],

  responsive: {
    prop: 'responsive',
    breakpointProp: 'breakpoint',
    defaultBreakpoint: 768,
    behavior: 'When viewport < breakpoint and responsive=true, position overrides to bottom, max-height constrains to 85vh, handle slot auto-renders, border-radius switches to top-only rounded corners',
    implementation: 'Internal useMediaQuery hook. Content reads effective position from context. Animation axis switches from translateX to translateY.',
  },

  renderContracts: [
    { id: 'animation-context', description: 'Root provides DrawerContext with isClosing, close(), onCloseComplete, and animation config to all sub-components' },
    { id: 'close-after-exit', description: 'Close button triggers isClosing state; Content exit animation calls onCloseComplete which actually unmounts the drawer' },
    { id: 'radix-open-override', description: 'Root keeps Radix open during exit animation (open={open || isClosing}) and ignores Radix close requests' },
    { id: 'content-portaled-font', description: 'Content is rendered in a portal and declares font-family: var(--move-font-body) to ensure correct typography outside the tree' },
    { id: 'position-aware-animation', description: 'Content determines slide axis (X or Y) and direction (positive or negative) based on effective position (respecting responsive override)' },
    { id: 'responsive-position-override', description: 'When responsive=true and viewport < breakpoint, Content overrides position to bottom regardless of prop value' },
    { id: 'handle-auto-render', description: 'Handle renders automatically in bottom-sheet mode (responsive override active); hidden in side-panel mode unless explicitly included' },
    { id: 'escape-triggers-animated-close', description: 'Escape key and pointer-down-outside trigger animated close via context close() instead of Radix default unmount' },
  ],

  tokens: [
    { name: '--move-drawer-overlay-bg', value: 'var(--move-overlay-heavy)', description: 'Overlay backdrop color' },
    { name: '--move-drawer-overlay-backdrop-blur', value: 'var(--move-overlay-blur)', description: 'Overlay backdrop blur amount' },
    { name: '--move-drawer-content-bg', value: 'var(--move-bg-subtle)', description: 'Content panel background' },
    { name: '--move-drawer-content-border', value: 'var(--move-border-base)', description: 'Content panel border color (inner edge only)' },
    { name: '--move-drawer-content-shadow', value: 'var(--move-shadow-overlay)', description: 'Content panel box shadow' },
    { name: '--move-drawer-content-padding', value: 'var(--move-spacing-lg)', description: 'Content panel padding' },
    { name: '--move-drawer-content-width-xs', value: '16rem', description: 'Content width for size xs' },
    { name: '--move-drawer-content-width-sm', value: '20rem', description: 'Content width for size sm' },
    { name: '--move-drawer-content-width-md', value: '24rem', description: 'Content width for size md' },
    { name: '--move-drawer-content-width-lg', value: '32rem', description: 'Content width for size lg' },
    { name: '--move-drawer-content-width-xl', value: '40rem', description: 'Content width for size xl' },
    { name: '--move-drawer-content-max-height-bottom', value: '85vh', description: 'Max height when in bottom-sheet mode' },
    { name: '--move-drawer-content-radius', value: '0', description: 'Content border radius (0 for edge-anchored panels)' },
    { name: '--move-drawer-content-radius-bottom', value: 'var(--move-rounded-xl)', description: 'Top border radius in bottom-sheet mode' },
    { name: '--move-drawer-title-font-size', value: 'var(--move-size-lg)', description: 'Title font size' },
    { name: '--move-drawer-title-font-weight', value: 'var(--move-weight-semibold)', description: 'Title font weight' },
    { name: '--move-drawer-title-fg', value: 'var(--move-fg-base)', description: 'Title text color' },
    { name: '--move-drawer-description-font-size', value: 'var(--move-size-sm)', description: 'Description font size' },
    { name: '--move-drawer-description-fg', value: 'var(--move-fg-muted)', description: 'Description text color' },
    { name: '--move-drawer-close-size', value: 'var(--move-space-8)', description: 'Close button width and height' },
    { name: '--move-drawer-close-icon-size', value: 'var(--move-text-base)', description: 'Close button icon size' },
    { name: '--move-drawer-close-fg', value: 'var(--move-fg-muted)', description: 'Close button text color' },
    { name: '--move-drawer-close-fg-hover', value: 'var(--move-fg-base)', description: 'Close button text color on hover' },
    { name: '--move-drawer-close-bg-hover', value: 'var(--move-bg-muted)', description: 'Close button background on hover' },
    { name: '--move-drawer-close-radius', value: 'var(--move-rounded-sm)', description: 'Close button border radius' },
    { name: '--move-drawer-handle-width', value: '2.5rem', description: 'Handle bar width' },
    { name: '--move-drawer-handle-height', value: '0.25rem', description: 'Handle bar height' },
    { name: '--move-drawer-handle-bg', value: 'var(--move-fg-muted)', description: 'Handle bar background color' },
    { name: '--move-drawer-handle-radius', value: 'var(--move-rounded-full)', description: 'Handle bar border radius' },
    { name: '--move-drawer-handle-margin', value: 'var(--move-spacing-sm)', description: 'Handle bar vertical margin' },
  ],

  variants: {
    position: {
      left: { description: 'Slides in from the left edge' },
      right: { description: 'Slides in from the right edge' },
      top: { description: 'Slides in from the top edge' },
      bottom: { description: 'Slides in from the bottom edge' },
    },
  },
  sizes: ['xs', 'sm', 'md', 'lg', 'xl', 'full'] as string[],

  labels: [],

  radixPrimitive: 'Dialog',
  hasHook: false,
  engineImports: ['withMoveComponent', 'useMergedRef', 'useControlledState'] as string[],

  componentDeps: [] as string[],

  childrenKind: 'composition' as const,

  testing: {
    behaviors: [
      'Root manages open/close state with controlled and uncontrolled patterns',
      'Root keeps drawer mounted during exit animation (open || isClosing)',
      'Root ignores Radix onOpenChange(false) — closing is driven by close()',
      'Trigger opens the drawer on click',
      'Content renders with data-position attribute matching effective position',
      'Content renders with data-size attribute matching size prop',
      'Content defaults to position right and size md',
      'Content position left anchors to left edge with full height',
      'Content position right anchors to right edge with full height',
      'Content position top anchors to top edge with full width',
      'Content position bottom anchors to bottom edge with full width',
      'Content size xs sets width to 16rem (left/right) or height to 16rem (top/bottom)',
      'Content size full sets width/height to 100%',
      'Content responsive=true switches position to bottom below breakpoint',
      'Content responsive=false preserves original position at all viewports',
      'Content renders Handle automatically in bottom-sheet responsive mode',
      'Content applies top-only border-radius in bottom-sheet mode',
      'Content constrains max-height to 85vh in bottom-sheet mode',
      'Close button triggers animated close via context instead of immediate unmount',
      'Overlay and Content are rendered inside Portal',
      'Header lays out title and close button with space-between',
      'Body is scrollable (overflow: auto)',
      'Footer provides flex layout for action buttons',
      'Handle renders a centered horizontal bar',
      'Forwards className and style on all factory sub-components',
    ],
    keyboard: [
      'Escape key triggers animated close',
    ],
    aria: [
      'Content has role=dialog from Radix',
      'Content has aria-modal from Radix',
      'Title provides aria-labelledby association from Radix',
      'Description provides aria-describedby association from Radix',
      'Close button has focus-visible outline',
    ],
    animation: [
      'Content entrance slides from edge using spring (sidebar ease)',
      'Content exit slides back to edge using snappy ease',
      'Content slide direction matches position (translateX for left/right, translateY for top/bottom)',
      'Content slide direction is negative for left/top, positive for right/bottom',
      'Responsive mode switches animation axis when position overrides to bottom',
      'Overlay entrance fades in (200ms)',
      'Overlay exit fades out (150ms)',
      'Content exit animation calls onCloseComplete to unmount drawer',
      'animations={false} disables all animations and immediately unmounts on close',
      'Reduced motion preference skips animations',
    ],
  },

  defaultReview: {
    status: 'approved' as const,
    decisionSource: 'rule-based' as const,
    overrides: {},
  },
};
