// Generated from DatePicker.spec.ts (schemaVersion: 6, specHash: 891de3de)

export const meta = {
  name: 'DatePicker',
  kind: 'compound' as const,
  category: 'form',
  description:
    'Date selection input with calendar popup, supporting single, range, and multiple modes with optional time picker',
  anatomy: ['Root', 'Trigger', 'Input', 'Icon', 'Portal', 'Content'],
  controlled: { pattern: 'open' as const },
  props: {
    Root: [
      'animate',
      'open',
      'defaultOpen',
      'onOpenChange',
      'closeOnSelect',
      'mode',
      'value',
      'defaultValue',
      'onValueChange',
      'events',
      'locale',
      'weekStartsOn',
      'constraints',
      'numberOfMonths',
      'showWeekNumbers',
      'yearRange',
      'fixedWeeks',
      'renderDayCell',
      'renderEvent',
      'placeholder',
      'rangeLabels',
      'labels',
      'showTime',
      'children',
      'className',
      'style',
    ],
    Trigger: ['children', 'className', 'style'],
    Input: ['placeholder', 'size', 'className', 'style'],
    Icon: ['children', 'className'],
    Portal: ['children', 'container'],
    Content: ['sideOffset', 'align', 'children', 'className', 'style'],
  },
  tokens: [
    '--move-datepicker-content-bg',
    '--move-datepicker-content-border',
    '--move-datepicker-content-radius',
    '--move-datepicker-content-shadow',
    '--move-datepicker-content-padding',
  ],
  dependencies: ['InputText', 'TimeField', 'Button', 'Icon', 'Calendar'],
};
