// Sidebar.spec.ts — Component specification
// specHash: PLACEHOLDER

export const spec = {
  schemaVersion: 6 as const,
  name: 'Sidebar',
  componentClass: 'disclosure' as const,
  category: 'panel',
  description: 'Collapsible navigation sidebar with icon-only mode, mobile portal overlay, item tooltips, and staggered entrance animations',

  compound: true,
  rootElement: 'aside',
  slots: [
    { name: 'root', element: 'aside', description: 'Main sidebar container with animated width collapse' },
    { name: 'overlay', element: 'div', description: 'Mobile backdrop overlay that dismisses the sidebar on click' },
    { name: 'header', element: 'div', description: 'Sticky header area at top of sidebar' },
    { name: 'content', element: 'div', description: 'Scrollable middle content area with staggered item entrance' },
    { name: 'footer', element: 'div', description: 'Sticky footer area at bottom of sidebar' },
    { name: 'group', element: 'div', description: 'Section grouping container for nav items' },
    { name: 'groupLabel', element: 'div', description: 'Section heading label that hides when collapsed' },
    { name: 'item', element: 'button', description: 'Interactive nav item with icon, label, and badge' },
    { name: 'itemIcon', element: 'span', description: 'Icon container within an item' },
    { name: 'itemLabel', element: 'span', description: 'Label text within an item, hidden when collapsed' },
    { name: 'itemBadge', element: 'span', description: 'Badge container within an item, hidden when collapsed' },
    { name: 'trigger', element: 'button', description: 'Toggle button for collapse/expand or mobile open/close' },
    { name: 'rail', element: 'div', description: 'Thin edge bar for re-expanding collapsed sidebar on click' },
  ],

  subComponents: [
    {
      name: 'Provider',
      slots: [],
      props: [
        { name: 'children', type: 'React.ReactNode', moveSpecific: false, description: 'App content including sidebar and main area' },
        { name: 'collapsed', type: 'boolean', moveSpecific: false, description: 'Controlled collapsed state' },
        { name: 'defaultCollapsed', type: 'boolean', default: 'false', moveSpecific: false, description: 'Initial collapsed state (uncontrolled)' },
        { name: 'onCollapsedChange', type: '(collapsed: boolean) => void', moveSpecific: false, description: 'Called when collapsed state changes' },
        { name: 'mobileOpen', type: 'boolean', moveSpecific: false, description: 'Controlled mobile open state' },
        { name: 'defaultMobileOpen', type: 'boolean', default: 'false', moveSpecific: false, description: 'Initial mobile open state (uncontrolled)' },
        { name: 'onMobileOpenChange', type: '(open: boolean) => void', moveSpecific: false, description: 'Called when mobile open state changes' },
        { name: 'breakpoint', type: 'number', default: '768', moveSpecific: false, description: 'Viewport width breakpoint for mobile mode' },
        { name: 'animate', type: 'LayerAnimate | false', moveSpecific: true, description: 'Animation config or false to disable all sidebar animations' },
      ],
      usesFactory: false,
      description: 'Context provider wrapping useSidebar hook, shares collapsed/mobile state and animation config',
    },
    {
      name: 'Root',
      slots: [{ name: 'root', element: 'aside', description: 'Sidebar aside container' }],
      props: [
        { name: 'children', type: 'React.ReactNode', moveSpecific: false, description: 'Sidebar sections (Header, Content, Footer)' },
        { name: 'className', type: 'string', moveSpecific: false, description: 'CSS class name' },
        { name: 'style', type: 'React.CSSProperties', moveSpecific: false, description: 'Inline styles' },
        { name: 'side', type: "'left' | 'right'", default: "'left'", moveSpecific: true, description: 'Which side the sidebar appears on' },
      ],
      usesFactory: true,
      description: 'Aside container with animated width transitions on collapse, portaled to body on mobile with overlay',
    },
    {
      name: 'Overlay',
      slots: [{ name: 'overlay', element: 'div', description: 'Mobile backdrop' }],
      props: [
        { name: 'className', type: 'string', moveSpecific: false, description: 'CSS class name' },
        { name: 'style', type: 'React.CSSProperties', moveSpecific: false, description: 'Inline styles' },
      ],
      usesFactory: true,
      description: 'Fixed backdrop overlay for mobile mode, closes sidebar on click, animated opacity entrance',
    },
    {
      name: 'Header',
      slots: [{ name: 'header', element: 'div', description: 'Sticky header' }],
      props: [
        { name: 'children', type: 'React.ReactNode', moveSpecific: false, description: 'Header content' },
        { name: 'className', type: 'string', moveSpecific: false, description: 'CSS class name' },
        { name: 'style', type: 'React.CSSProperties', moveSpecific: false, description: 'Inline styles' },
        { name: 'collapsedChildren', type: 'React.ReactNode', moveSpecific: true, description: 'Alternative content shown when sidebar is collapsed (desktop only)' },
      ],
      usesFactory: true,
      description: 'Sticky header with border-bottom, supports collapsed content swap',
    },
    {
      name: 'Content',
      slots: [{ name: 'content', element: 'div', description: 'Scrollable content area' }],
      props: [
        { name: 'children', type: 'React.ReactNode', moveSpecific: false, description: 'Navigation items and groups' },
        { name: 'className', type: 'string', moveSpecific: false, description: 'CSS class name' },
        { name: 'style', type: 'React.CSSProperties', moveSpecific: false, description: 'Inline styles' },
      ],
      usesFactory: true,
      description: 'Scrollable middle area with staggered entrance animation on items',
    },
    {
      name: 'Footer',
      slots: [{ name: 'footer', element: 'div', description: 'Sticky footer' }],
      props: [
        { name: 'children', type: 'React.ReactNode', moveSpecific: false, description: 'Footer content' },
        { name: 'className', type: 'string', moveSpecific: false, description: 'CSS class name' },
        { name: 'style', type: 'React.CSSProperties', moveSpecific: false, description: 'Inline styles' },
      ],
      usesFactory: true,
      description: 'Sticky footer with border-top, centers items when collapsed',
    },
    {
      name: 'Group',
      slots: [{ name: 'group', element: 'div', description: 'Group container' }],
      props: [
        { name: 'children', type: 'React.ReactNode', moveSpecific: false, description: 'GroupLabel and Item children' },
        { name: 'className', type: 'string', moveSpecific: false, description: 'CSS class name' },
        { name: 'style', type: 'React.CSSProperties', moveSpecific: false, description: 'Inline styles' },
      ],
      usesFactory: true,
      description: 'Section grouping container with role=group, separated by borders when collapsed',
    },
    {
      name: 'GroupLabel',
      slots: [{ name: 'groupLabel', element: 'div', description: 'Section heading' }],
      props: [
        { name: 'children', type: 'React.ReactNode', moveSpecific: false, description: 'Label text' },
        { name: 'className', type: 'string', moveSpecific: false, description: 'CSS class name' },
        { name: 'style', type: 'React.CSSProperties', moveSpecific: false, description: 'Inline styles' },
      ],
      usesFactory: true,
      description: 'Uppercase section label hidden when sidebar is collapsed',
    },
    {
      name: 'Item',
      slots: [
        { name: 'item', element: 'button', description: 'Nav item container' },
        { name: 'itemIcon', element: 'span', description: 'Item icon wrapper' },
        { name: 'itemLabel', element: 'span', description: 'Item label text' },
        { name: 'itemBadge', element: 'span', description: 'Item badge wrapper' },
      ],
      props: [
        { name: 'children', type: 'React.ReactNode', moveSpecific: false, description: 'Item label text content' },
        { name: 'className', type: 'string', moveSpecific: false, description: 'CSS class name' },
        { name: 'style', type: 'React.CSSProperties', moveSpecific: false, description: 'Inline styles' },
        { name: 'icon', type: 'React.ReactNode', moveSpecific: true, description: 'Icon element rendered before label' },
        { name: 'badge', type: 'React.ReactNode', moveSpecific: true, description: 'Badge element rendered after label' },
        { name: 'active', type: 'boolean', moveSpecific: true, description: 'Whether this item is the active/selected item' },
        { name: 'disabled', type: 'boolean', moveSpecific: true, description: 'Disable interaction' },
        { name: 'asChild', type: 'boolean', moveSpecific: true, description: 'Merge props onto child element (e.g. an anchor tag) instead of rendering a button' },
        { name: 'tooltip', type: 'React.ReactNode', moveSpecific: true, description: 'Tooltip content shown when sidebar is collapsed on desktop' },
      ],
      usesFactory: true,
      description: 'Interactive nav item with icon, label, badge slots; shows tooltip when collapsed; supports asChild for custom elements',
    },
    {
      name: 'Trigger',
      slots: [{ name: 'trigger', element: 'button', description: 'Toggle button' }],
      props: [
        { name: 'children', type: 'React.ReactNode', moveSpecific: false, description: 'Trigger content (typically a hamburger/collapse icon)' },
        { name: 'className', type: 'string', moveSpecific: false, description: 'CSS class name' },
        { name: 'style', type: 'React.CSSProperties', moveSpecific: false, description: 'Inline styles' },
        { name: 'asChild', type: 'boolean', moveSpecific: true, description: 'Merge props onto child element instead of wrapping in button' },
      ],
      usesFactory: true,
      description: 'Toggle button that collapses/expands on desktop or opens/closes on mobile',
    },
    {
      name: 'Rail',
      slots: [{ name: 'rail', element: 'div', description: 'Edge bar' }],
      props: [
        { name: 'className', type: 'string', moveSpecific: false, description: 'CSS class name' },
        { name: 'style', type: 'React.CSSProperties', moveSpecific: false, description: 'Inline styles' },
      ],
      usesFactory: true,
      description: 'Thin edge bar on sidebar border, clicks to toggle collapsed state, aria-hidden',
    },
  ],

  props: [],

  anatomy: {
    slot: 'root',
    dataAttributes: ['data-collapsed', 'data-side', 'data-mobile'],
    children: [
      {
        slot: 'header',
        children: [],
      },
      {
        slot: 'content',
        children: [
          {
            slot: 'group',
            ariaAttributes: ['role=group'],
            children: [
              { slot: 'groupLabel' },
              {
                slot: 'item',
                dataAttributes: ['data-active', 'data-disabled'],
                children: [
                  { slot: 'itemIcon' },
                  { slot: 'itemLabel' },
                  { slot: 'itemBadge' },
                ],
              },
            ],
          },
        ],
      },
      {
        slot: 'footer',
        children: [],
      },
      { slot: 'rail' },
    ],
  },

  controlled: 'open' as const,
  controlledProps: {
    valueProp: 'collapsed',
    defaultValueProp: 'defaultCollapsed',
    onChangeProp: 'onCollapsedChange',
  },
  keyboard: null,
  focus: null,
  formType: null,
  asChild: true,

  animations: [
    {
      slot: 'root',
      hook: 'useLifecycleAnimate',
      configType: 'LifecycleAnimate',
      defaultConfig: "{ width: targetWidth, ease: spring({ mass: 1, stiffness: 300, damping: 25, velocity: 0 }) }",
    },
    {
      slot: 'overlay',
      hook: 'useLifecycleAnimate',
      configType: 'LifecycleAnimate',
      defaultConfig: "{ opacity: [0, 1], ease: 'outQuart', duration: 200 }",
    },
    {
      slot: 'content',
      hook: 'useLifecycleAnimate',
      configType: 'LifecycleAnimate & StaggerModifier',
      defaultConfig: "{ opacity: [0, 1], translateX: [-8, 0], ease: spring({ mass: 1, stiffness: 300, damping: 25 }), stagger: { delay: 30 } }",
    },
  ],

  renderContracts: [
    { id: 'mobile-portal', description: 'On mobile (viewport < breakpoint), Root is portaled to document.body with an Overlay backdrop. Returns null when mobileOpen is false.' },
    { id: 'overlay-dismisses', description: 'Clicking the mobile overlay calls setMobileOpen(false) to close the sidebar.' },
    { id: 'overlay-aria-hidden', description: 'Overlay element has aria-hidden="true" since it is purely decorative.' },
    { id: 'rail-aria-hidden', description: 'Rail element has aria-hidden="true" since it is a convenience click target.' },
    { id: 'collapsed-width-spring', description: 'Desktop width animation uses anime.js spring from expanded to collapsed width, reading CSS variables --move-sidebar-width and --move-sidebar-width-collapsed.' },
    { id: 'collapsed-skip-first-render', description: 'Width animation skips the first render so CSS handles initial state without a flash.' },
    { id: 'collapsed-hides-labels', description: 'When collapsed (desktop), itemLabel and itemBadge are hidden via CSS (opacity: 0, width: 0). GroupLabel is also hidden.' },
    { id: 'item-tooltip-collapsed', description: 'When collapsed on desktop, Item wraps its element in a Tooltip (side="right", sideOffset=8) if tooltip prop is provided.' },
    { id: 'item-as-child', description: 'When asChild=true, Item clones the single child element and injects icon/label/badge as its content instead of rendering a button.' },
    { id: 'header-collapsed-content', description: 'Header shows collapsedChildren when collapsed on desktop, falls back to children if collapsedChildren is not provided.' },
    { id: 'trigger-mobile-toggle', description: 'Trigger calls toggleMobileOpen on mobile and toggleCollapsed on desktop.' },
    { id: 'content-stagger-items', description: 'Content entrance animation staggers .item elements with translateX(-8) to 0 and opacity 0 to 1.' },
    { id: 'group-role', description: 'Group renders with role="group" for accessibility grouping.' },
    { id: 'provider-context', description: 'Provider wraps useSidebar hook and exposes state via SidebarContext. All sub-components consume context via useSidebarContext().' },
    { id: 'animate-false-disables-all', description: 'When Provider receives animate={false}, all anime.js animations are disabled across Root, Overlay, and Content.' },
  ],

  tokens: [
    { name: '--move-sidebar-width', value: '15rem', description: 'Expanded sidebar width' },
    { name: '--move-sidebar-width-collapsed', value: '4rem', description: 'Collapsed sidebar width (icon-only mode)' },
    { name: '--move-sidebar-width-mobile', value: '18rem', description: 'Mobile sidebar width' },
    { name: '--move-sidebar-bg', value: 'var(--move-bg-subtle)', description: 'Sidebar background color' },
    { name: '--move-sidebar-border', value: 'var(--move-border-base)', description: 'Sidebar border color' },
    { name: '--move-sidebar-fg', value: 'var(--move-fg-base)', description: 'Sidebar text color' },
    { name: '--move-sidebar-item-radius', value: 'var(--move-rounded-md)', description: 'Item border radius' },
    { name: '--move-sidebar-item-padding-x', value: 'var(--move-spacing-md)', description: 'Item horizontal padding' },
    { name: '--move-sidebar-item-padding-y', value: 'var(--move-spacing-sm)', description: 'Item vertical padding' },
    { name: '--move-sidebar-item-fg', value: 'var(--move-fg-muted)', description: 'Item text color' },
    { name: '--move-sidebar-item-fg-hover', value: 'var(--move-fg-base)', description: 'Item text color on hover' },
    { name: '--move-sidebar-item-fg-active', value: 'var(--move-primary-fg)', description: 'Active item text color' },
    { name: '--move-sidebar-item-bg-hover', value: 'var(--move-bg-muted)', description: 'Item background on hover' },
    { name: '--move-sidebar-item-bg-active', value: 'var(--move-primary)', description: 'Active item background' },
    { name: '--move-sidebar-group-label-fg', value: 'var(--move-fg-subtle)', description: 'Group label text color' },
    { name: '--move-sidebar-group-label-size', value: 'var(--move-size-xs)', description: 'Group label font size' },
  ],

  variants: {},
  sizes: [] as string[],

  labels: [],

  radixPrimitive: 'Slot',

  hasHook: true,
  engineImports: ['withMoveComponent', 'useMergedRef', 'useControlledState'] as string[],
  animationImports: ['prefersReducedMotion'] as string[],
  componentDeps: ['Tooltip'] as string[],

  testing: {
    behaviors: [
      'Provider renders children with sidebar context',
      'Provider useSidebar hook manages collapsed and mobileOpen state',
      'Root renders aside element with data-collapsed, data-side, data-mobile',
      'Root defaults side to left',
      'Root side=right sets border-left instead of border-right',
      'Root is portaled to body on mobile when mobileOpen is true',
      'Root returns null on mobile when mobileOpen is false',
      'Overlay renders on mobile with fixed backdrop',
      'Overlay click closes mobile sidebar',
      'Header renders with border-bottom',
      'Header shows collapsedChildren when collapsed on desktop',
      'Header falls back to children when collapsedChildren is undefined',
      'Content renders scrollable area',
      'Footer renders with border-top',
      'Footer centers items when collapsed',
      'Group renders with role=group',
      'GroupLabel hidden when collapsed (opacity: 0, height: 0)',
      'Item renders button with icon, label, badge slots',
      'Item asChild clones child element with injected slots',
      'Item active state sets data-active and primary background',
      'Item disabled state sets data-disabled and reduced opacity',
      'Item shows tooltip when collapsed on desktop with tooltip prop',
      'Item does not show tooltip when expanded',
      'Item does not show tooltip on mobile even when collapsed',
      'Collapsed items center icons and hide labels/badges',
      'Trigger calls toggleCollapsed on desktop click',
      'Trigger calls toggleMobileOpen on mobile click',
      'Trigger supports asChild via Slot.Root',
      'Rail click calls toggleCollapsed',
      'Rail has aria-hidden=true',
      'Forwards className and style on all sub-components',
      'Controlled collapsed/onCollapsedChange works correctly',
      'Uncontrolled defaultCollapsed works correctly',
      'Breakpoint prop controls mobile mode threshold',
      'Auto-closes mobile sheet when viewport crosses to desktop',
    ],
    keyboard: [
      'Items are focusable via tab',
      'Trigger is keyboard accessible',
    ],
    aria: [
      'Root renders as aside element for landmark navigation',
      'Overlay has aria-hidden=true',
      'Rail has aria-hidden=true',
      'Group has role=group',
      'Disabled items have data-disabled',
    ],
    animation: [
      'Root width animates with spring on collapse/expand',
      'Root width animation skips first render',
      'Root width animation disabled when animate=false',
      'Overlay opacity entrance animation plays on mobile open',
      'Overlay animation disabled when animate=false',
      'Content staggers item entrance with translateX and opacity',
      'Content stagger animation disabled when animate=false',
      'All animations respect prefersReducedMotion',
    ],
  },

  defaultReview: {
    status: 'approved' as const,
    decisionSource: 'user-confirmed' as const,
    overrides: {},
  },
};
